openapi: 3.0.1
info:
  title: WeatherAPI
  description: API Definition of WeatherAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/weatherapi
paths:
  /:
    get:
      responses:
        default:
          description: Default response
